/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BlankKeycap: typeof import('./components/Characters/BlankKeycap.vue')['default']
    BlankKeycapModel: typeof import('./components/Models/BlankKeycapModel.vue')['default']
    Character: typeof import('./components/Character.vue')['default']
    CharacterPhone: typeof import('./components/CharacterPhone.vue')['default']
    CircuitCoral: typeof import('./components/Characters/CircuitCoral.vue')['default']
    CircuitCoralModel: typeof import('./components/Models/CircuitCoralModel.vue')['default']
    CodeGardenEel: typeof import('./components/Characters/CodeGardenEel.vue')['default']
    CodeGardenEelModel: typeof import('./components/Models/CodeGardenEelModel.vue')['default']
    FilmCrab: typeof import('./components/Characters/FilmCrab.vue')['default']
    FilmCrabModel: typeof import('./components/Models/FilmCrabModel.vue')['default']
    FountainPenSquid: typeof import('./components/Characters/FountainPenSquid.vue')['default']
    FountainPenSquidModel: typeof import('./components/Models/FountainPenSquidModel.vue')['default']
    JellyFish: typeof import('./components/Characters/JellyFish.vue')['default']
    JellyFishModel: typeof import('./components/Models/JellyFishModel.vue')['default']
    JoystickJellyfishKeycap: typeof import('./components/Characters/JoystickJellyfishKeycap.vue')['default']
    JoystickJellyfishKeycapModel: typeof import('./components/Models/JoystickJellyfishKeycapModel.vue')['default']
    LensCrab: typeof import('./components/Characters/LensCrab.vue')['default']
    LensCrabModel: typeof import('./components/Models/LensCrabModel.vue')['default']
    RadarChart: typeof import('./components/Charts/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section1: typeof import('./components/Section1.vue')['default']
    Section2: typeof import('./components/Section2.vue')['default']
    Stingray: typeof import('./components/Characters/Stingray.vue')['default']
    StingrayModel: typeof import('./components/Models/StingrayModel.vue')['default']
    VcardGroupBackup: typeof import('./components/VcardGroupBackup.vue')['default']
  }
}
